pipeline {
    agent any
    stages {
        stage('Copy Repo') {
            steps{
                checkout scm
                sh 'ls *'
            }
        }
        stage('Terraform stage') {
            steps{
                echo 'Executing Terraform steps'
                sh """
                cd TerraforminJenkins
                terraform init
                terraform plan
                terraform apply --auto-approve
                """
                sh pwd
            }
        }
        stage('Time to Destroy') {
            steps{
                Input message: 'Destroy Resources'
            }
        }
    }    
}