pipeline {
    agent any
    environment {
        DOCKER_CREDS = credentials('docker_creds')
    }
    stages {
        stage('Clean Up') {
            steps {
                deleteDir()
            }
        }
        stage('clone Repo') {
            steps {
                checkout scm
                sh 'ls *'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t venu1322/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }
        stage('Docker login') {
            steps {
                //sh 'docker login -u $DOCKER_CREDS_USR -p $DOCKER_CREDS_PSW'
                sh 'echo $DOCKER_CREDS_PSW | docker login -u $DOCKER_CREDS_USR --password-stdin'
            }
        }
        stage('Docker Push') {
            steps {
                sh 'docker push venu1322/jenkinstest:$BUILD_NUMBER'
            }
        }
    }
    post {
        always {
            sh 'docker logout'
        }
    }
}