pipeline {
    agent any
    stages {
        stage('Build-Stage') {
            steps {
                echo 'Build stage'
            }
        }
        stage('Test stage') {
            steps {
                echo 'Testing stage steps'
            }
        }
        stage('Deploy-stage') {
            steps {
                echo "Deploy stage"
            }
        }
    }
}